# Generated by Django 5.1.5 on 2025-03-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_email_user_full_name_user_melicode_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='full_name'),
        ),
    ]
