# Generated by Django 5.1.5 on 2025-03-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Public Ads will be displayed in the api views.', verbose_name='is public'),
        ),
    ]
