# Generated by Django 5.1.5 on 2025-03-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='publisher',
        ),
    ]
